version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket lab-hello-world-code-pipeline --template-file template.yaml
artifacts:
  files:
    - packaged.yaml
