version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket lab-hello-world-code-pipeline --output-template-file packaged.yaml
      # - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket lab-hello-world-code-pipeline --stack-name sam-pipeline-test
artifacts:
  files:
    - packaged.yaml
  name: BuildOutput
